#ifndef OPTIONS_H
#define OPTIONS_H

#define USE_SMALL_ZP 0

#define ENABLE_SOURCE_APPEND_DEBUG 0
#define ENABLE_OUTPUT_BLOCK_DEBUG 0
#define ENABLE_ASSEMBLER_INSTRUCTION_ENCODE_DEBUG 0
#define ENABLE_ASSEMBLER_PASS_CONTROL_DEBUG 0

#endif
